"""create rag foundation contracts

Revision ID: 11832204f394
Revises: 8328db50703a
Create Date: 2025-12-29 19:33:13.484045

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import VECTOR

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11832204f394'
down_revision: Union[str, Sequence[str], None] = '8328db50703a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")

    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('doc_id', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('ingestion_pipeline_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_created_at', 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_doc_id'), 'documents', ['doc_id'], unique=True)
    op.create_index('ix_documents_source_type_created_at', 'documents', ['source_type', 'created_at'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('pipeline_version', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stats_json', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_run_id'), 'ingestion_runs', ['run_id'], unique=True)
    op.create_table('rag_queries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_model_version', sa.String(length=64), nullable=True),
    sa.Column('embedding_model_version', sa.String(length=64), nullable=False),
    sa.Column('citations_json', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_queries_session_id'), 'rag_queries', ['session_id'], unique=True)
    op.create_table('retrieval_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('retrieval_id', sa.String(length=64), nullable=False),
    sa.Column('doc_id', sa.String(length=128), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('embedding_model_version', sa.String(length=64), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('results_json', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieval_logs_doc_id'), 'retrieval_logs', ['doc_id'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_retrieval_id'), 'retrieval_logs', ['retrieval_id'], unique=True)
    op.create_table('document_chunks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_id', sa.String(length=160), nullable=False),
    sa.Column('doc_id', sa.String(length=128), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('start_ref', sa.String(length=128), nullable=True),
    sa.Column('end_ref', sa.String(length=128), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.doc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id', 'ordinal', name='uq_document_chunks_doc_id_ordinal')
    )
    op.create_index(op.f('ix_document_chunks_chunk_id'), 'document_chunks', ['chunk_id'], unique=True)
    op.create_index(op.f('ix_document_chunks_doc_id'), 'document_chunks', ['doc_id'], unique=False)
    op.create_table('user_feedback',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('feedback_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_helpful', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['rag_queries.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_feedback_feedback_id'), 'user_feedback', ['feedback_id'], unique=True)
    op.create_index(op.f('ix_user_feedback_session_id'), 'user_feedback', ['session_id'], unique=False)
    op.create_table('chunk_embeddings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_id', sa.String(length=160), nullable=False),
    sa.Column('embedding_model_version', sa.String(length=64), nullable=False),
    sa.Column('embedding', VECTOR(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.chunk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'embedding_model_version', name='uq_chunk_embeddings_chunk_model')
    )
    op.create_index(op.f('ix_chunk_embeddings_chunk_id'), 'chunk_embeddings', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_approval_items_status'), 'approval_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_items_status'), table_name='approval_items')
    op.drop_index(op.f('ix_chunk_embeddings_chunk_id'), table_name='chunk_embeddings')
    op.drop_table('chunk_embeddings')
    op.drop_index(op.f('ix_user_feedback_session_id'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_feedback_id'), table_name='user_feedback')
    op.drop_table('user_feedback')
    op.drop_index(op.f('ix_document_chunks_doc_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chunk_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_retrieval_logs_retrieval_id'), table_name='retrieval_logs')
    op.drop_index(op.f('ix_retrieval_logs_doc_id'), table_name='retrieval_logs')
    op.drop_table('retrieval_logs')
    op.drop_index(op.f('ix_rag_queries_session_id'), table_name='rag_queries')
    op.drop_table('rag_queries')
    op.drop_index(op.f('ix_ingestion_runs_run_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index('ix_documents_source_type_created_at', table_name='documents')
    op.drop_index(op.f('ix_documents_doc_id'), table_name='documents')
    op.drop_index('ix_documents_created_at', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
