"""create approval_items

Revision ID: 8328db50703a
Revises: 0dd3d96a7bdc
Create Date: 2025-12-22 18:48:53.964723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8328db50703a'
down_revision: Union[str, Sequence[str], None] = '0dd3d96a7bdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_items', sa.Column('title', sa.String(length=200), nullable=False))
    op.add_column('approval_items', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('approval_items', sa.Column('type', sa.String(length=64), nullable=False))
    op.add_column('approval_items', sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('approval_items', sa.Column('requested_by', sa.String(length=128), nullable=False))
    op.add_column('approval_items', sa.Column('assigned_to', sa.String(length=128), nullable=True))
    op.add_column('approval_items', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('approval_items', sa.Column('decision_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('approval_items', sa.Column('decision_by', sa.String(length=128), nullable=True))
    op.add_column('approval_items', sa.Column('decision_reason', sa.Text(), nullable=True))
    op.alter_column('approval_items', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('approval_items', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status'),
               existing_nullable=False)
    op.create_index('ix_approval_items_status_created_at', 'approval_items', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_approval_items_status_created_at', table_name='approval_items')
    op.alter_column('approval_items', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('approval_items', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('approval_items', 'decision_reason')
    op.drop_column('approval_items', 'decision_by')
    op.drop_column('approval_items', 'decision_at')
    op.drop_column('approval_items', 'updated_at')
    op.drop_column('approval_items', 'assigned_to')
    op.drop_column('approval_items', 'requested_by')
    op.drop_column('approval_items', 'payload_json')
    op.drop_column('approval_items', 'type')
    op.drop_column('approval_items', 'description')
    op.drop_column('approval_items', 'title')
    # ### end Alembic commands ###
